"""m3_job_groups_and_document_rendered_keys

F5.10 — Document now binds to a JobGroup (a user-named collection of
scored jobs sharing one tailored CV), not a single Job; a single-job
CV is just a group of one; JobGroup/JobGroupMember are new. Also
F5.2/F5.11 — rendered_pdf_key/rendered_docx_key replaced by a
rendered_keys JSONB map, since F5.2 needs two PDF-shaped renderer
outputs (LaTeX, HTML/CSS), never a DOCX. Both `documents` and
`claim_verifications` are confirmed empty (checked directly before
writing this) — this is a clean schema swap, not a data migration,
and the added NOT NULL columns need no server_default as a result.

Revision ID: 2874871f942d
Revises: 4aeaaa98b36f
Create Date: 2026-08-21 13:03:46.254783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2874871f942d'
down_revision: Union[str, Sequence[str], None] = '4aeaaa98b36f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_groups',
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], name=op.f('fk_job_groups_persona_id_personas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_groups'))
    )
    op.create_index(op.f('ix_job_groups_user_id'), 'job_groups', ['user_id'], unique=False)
    op.create_table('job_group_members',
    sa.Column('job_group_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_group_id'], ['job_groups.id'], name=op.f('fk_job_group_members_job_group_id_job_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_group_members_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_group_members')),
    sa.UniqueConstraint('job_group_id', 'job_id', name='uq_job_group_members_group_job')
    )
    op.add_column('documents', sa.Column('job_group_id', sa.UUID(), nullable=False))
    op.add_column('documents', sa.Column('rendered_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_constraint(op.f('fk_documents_job_id_jobs'), 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_documents_job_group_id_job_groups'), 'documents', 'job_groups', ['job_group_id'], ['id'], ondelete='CASCADE')
    op.drop_column('documents', 'job_id')
    op.drop_column('documents', 'rendered_docx_key')
    op.drop_column('documents', 'rendered_pdf_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('rendered_pdf_key', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('rendered_docx_key', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_documents_job_group_id_job_groups'), 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_documents_job_id_jobs'), 'documents', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.drop_column('documents', 'rendered_keys')
    op.drop_column('documents', 'job_group_id')
    op.drop_table('job_group_members')
    op.drop_index(op.f('ix_job_groups_user_id'), table_name='job_groups')
    op.drop_table('job_groups')
    # ### end Alembic commands ###
