"""credit_transaction_dodo_payment_id

Revision ID: 28e12898188f
Revises: 864362edc258
Create Date: 2026-09-04 02:41:45.652266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28e12898188f'
down_revision: Union[str, Sequence[str], None] = '864362edc258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_transactions', sa.Column('dodo_payment_id', sa.String(length=120), nullable=True))
    op.create_unique_constraint(op.f('uq_credit_transactions_dodo_payment_id'), 'credit_transactions', ['dodo_payment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_credit_transactions_dodo_payment_id'), 'credit_transactions', type_='unique')
    op.drop_column('credit_transactions', 'dodo_payment_id')
    # ### end Alembic commands ###
