"""m3_document_tex_overrides

Revision ID: 2a090e5a512b
Revises: 5b6ed0a0e12e
Create Date: 2026-08-21 14:30:04.138740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a090e5a512b'
down_revision: Union[str, Sequence[str], None] = '5b6ed0a0e12e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # `documents` has real rows now (confirmed: 2, from earlier live
    # verification of §2-§4) — a bare NOT NULL add_column would fail
    # against them, so this needs a server_default matching the
    # model's Python-side default (an empty JSONB object), same fix as
    # every other NOT-NULL-on-a-populated-table migration this project.
    op.add_column(
        'documents',
        sa.Column(
            'tex_overrides',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'tex_overrides')
    # ### end Alembic commands ###
