"""audio settings and catalog voices

Revision ID: 4503b55a4b56
Revises: e08ac9310ed3
Create Date: 2026-09-03 05:22:29.129737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4503b55a4b56'
down_revision: Union[str, Sequence[str], None] = 'e08ac9310ed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_settings',
    sa.Column('transcribe_catalog_entry_id', sa.UUID(), nullable=True),
    sa.Column('speech_catalog_entry_id', sa.UUID(), nullable=True),
    sa.Column('speech_voice', sa.String(length=80), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['speech_catalog_entry_id'], ['model_catalog_entries.id'], name=op.f('fk_audio_settings_speech_catalog_entry_id_model_catalog_entries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transcribe_catalog_entry_id'], ['model_catalog_entries.id'], name=op.f('fk_audio_settings_transcribe_catalog_entry_id_model_catalog_entries'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio_settings'))
    )
    op.create_index(op.f('ix_audio_settings_user_id'), 'audio_settings', ['user_id'], unique=False)
    op.add_column('model_catalog_entries', sa.Column('voices', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_catalog_entries', 'voices')
    op.drop_index(op.f('ix_audio_settings_user_id'), table_name='audio_settings')
    op.drop_table('audio_settings')
    # ### end Alembic commands ###
