"""per persona profiles clone and unique constraint

Revision ID: 4aeaaa98b36f
Revises: f35e8b06ed03
Create Date: 2026-08-21 09:42:22.575574

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4aeaaa98b36f'
down_revision: Union[str, Sequence[str], None] = 'f35e8b06ed03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Hand-written, not autogenerated — real data surgery, not DDL
    alone. Every persona is meant to own its own Profile + evidence
    bank exclusively now (F1.5), but nothing has enforced that until
    this migration; confirmed live before writing this that exactly
    one profile is shared today (Adrian's real 'AI Engineer' and
    'Kerja di Singapore' personas, both pointing at the same profile
    and its 20 real evidence items) — but this loops over every
    profile shared by >1 persona rather than hardcoding those two ids,
    so it stays correct if more exist by the time this actually runs.

    For each shared profile, the earliest-created persona keeps the
    existing profile row untouched; every other persona sharing it
    gets a byte-identical clone (including the evidence embeddings —
    same text, same model, no reason to re-embed and re-pay for it)
    and is repointed at its own copy. Which persona "keeps" the
    original is arbitrary since the clone is identical at the moment
    of migration; only which one is cheapest to leave alone matters.
    """
    conn = op.get_bind()

    shared_profile_ids = conn.execute(
        sa.text("SELECT profile_id FROM personas GROUP BY profile_id HAVING COUNT(*) > 1")
    ).fetchall()

    for (profile_id,) in shared_profile_ids:
        persona_rows = conn.execute(
            sa.text("SELECT id FROM personas WHERE profile_id = :pid ORDER BY created_at"),
            {"pid": profile_id},
        ).fetchall()

        # First (earliest-created) persona keeps the existing profile row as-is.
        for (persona_id,) in persona_rows[1:]:
            new_profile_id = uuid.uuid4()

            conn.execute(
                sa.text(
                    """
                    INSERT INTO profiles (
                        id, user_id, revision, raw_cv_object_key, parsed_profile,
                        parsed_at, confirmed, visa_status, notice_period_days,
                        created_at, updated_at
                    )
                    SELECT
                        :new_id, user_id, revision, raw_cv_object_key, parsed_profile,
                        parsed_at, confirmed, visa_status, notice_period_days,
                        now(), now()
                    FROM profiles WHERE id = :old_id
                    """
                ),
                {"new_id": new_profile_id, "old_id": profile_id},
            )

            conn.execute(
                sa.text(
                    """
                    INSERT INTO evidence_items (
                        id, user_id, profile_id, text, category, title, skills,
                        metrics, employer, date_start, date_end, verified, embedding,
                        created_at, updated_at
                    )
                    SELECT
                        gen_random_uuid(), user_id, :new_profile_id, text, category, title, skills,
                        metrics, employer, date_start, date_end, verified, embedding,
                        now(), now()
                    FROM evidence_items WHERE profile_id = :old_profile_id
                    """
                ),
                {"new_profile_id": new_profile_id, "old_profile_id": profile_id},
            )

            conn.execute(
                sa.text("UPDATE personas SET profile_id = :new_profile_id WHERE id = :persona_id"),
                {"new_profile_id": new_profile_id, "persona_id": persona_id},
            )

    op.create_unique_constraint(op.f("uq_personas_profile_id"), "personas", ["profile_id"])


def downgrade() -> None:
    """Intentionally partial: drops the uniqueness constraint only.
    Un-merging a clone back into a shared profile is ambiguous and
    lossy by nature (whichever edits happened on the clone since it
    was created have no well-defined home in a re-shared profile) —
    stated plainly rather than faked as fully reversible."""
    op.drop_constraint(op.f("uq_personas_profile_id"), "personas", type_="unique")
