"""application_attempt_email_draft

Revision ID: 4fb7ed683f80
Revises: 932bf23ce1f2
Create Date: 2026-08-24 11:18:28.927862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4fb7ed683f80'
down_revision: Union[str, Sequence[str], None] = '932bf23ce1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_attempts', sa.Column('email_draft', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_attempts', 'email_draft')
    # ### end Alembic commands ###
