"""preference multi select fields

Revision ID: 547887ea6409
Revises: 7fde5adc9727
Create Date: 2026-08-21 08:23:23.785858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '547887ea6409'
down_revision: Union[str, Sequence[str], None] = '7fde5adc9727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-written, not autogenerated: this table has a real row in it
    # (Adrian's own saved preferences, seniority='junior' among them) —
    # autogenerate's default drop-and-recreate for a type change would
    # have silently discarded it. `postgresql_using` instead converts
    # each existing scalar into a one-element array so it survives.
    op.alter_column(
        'preferences', 'seniority',
        type_=postgresql.ARRAY(sa.String()),
        postgresql_using="CASE WHEN seniority IS NULL THEN '{}'::varchar[] ELSE ARRAY[seniority] END",
        nullable=False,
        server_default='{}',
    )
    op.alter_column(
        'preferences', 'remote_policy',
        type_=postgresql.ARRAY(sa.String()),
        postgresql_using="CASE WHEN remote_policy IS NULL THEN '{}'::varchar[] ELSE ARRAY[remote_policy] END",
        nullable=False,
        server_default='{}',
    )
    op.alter_column(
        'preferences', 'company_size_pref',
        type_=postgresql.ARRAY(sa.String()),
        postgresql_using="CASE WHEN company_size_pref IS NULL THEN '{}'::varchar[] ELSE ARRAY[company_size_pref] END",
        nullable=False,
        server_default='{}',
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Lossy for any row with more than one selection (takes the first
    # array element only) — an inherent consequence of narrowing
    # multi-select back to one-of, not something a migration can avoid.
    op.alter_column(
        'preferences', 'company_size_pref',
        type_=sa.String(length=60),
        postgresql_using="company_size_pref[1]",
        nullable=True,
        server_default=None,
    )
    op.alter_column(
        'preferences', 'remote_policy',
        type_=sa.String(length=60),
        postgresql_using="remote_policy[1]",
        nullable=True,
        server_default=None,
    )
    op.alter_column(
        'preferences', 'seniority',
        type_=sa.String(length=60),
        postgresql_using="seniority[1]",
        nullable=True,
        server_default=None,
    )
