"""m3_skill_gap_items

Revision ID: 5b6ed0a0e12e
Revises: 2874871f942d
Create Date: 2026-08-21 13:37:47.503693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b6ed0a0e12e'
down_revision: Union[str, Sequence[str], None] = '2874871f942d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_gap_items',
    sa.Column('job_group_id', sa.UUID(), nullable=False),
    sa.Column('skill_text', sa.String(length=250), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('evidence_item_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_item_id'], ['evidence_items.id'], name=op.f('fk_skill_gap_items_evidence_item_id_evidence_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_group_id'], ['job_groups.id'], name=op.f('fk_skill_gap_items_job_group_id_job_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_gap_items')),
    sa.UniqueConstraint('job_group_id', 'skill_text', name='uq_skill_gap_items_group_skill')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill_gap_items')
    # ### end Alembic commands ###
