"""add run_events table

Revision ID: 5cd8a15cdcbc
Revises: f93e681079f8
Create Date: 2026-08-20 17:41:56.607618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cd8a15cdcbc'
down_revision: Union[str, Sequence[str], None] = 'f93e681079f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_events',
    sa.Column('agent_run_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_run_events_agent_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_events')),
    sa.UniqueConstraint('agent_run_id', 'seq', name='uq_run_events_run_seq')
    )
    op.create_index(op.f('ix_run_events_agent_run_id'), 'run_events', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_run_events_user_id'), 'run_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_events_user_id'), table_name='run_events')
    op.drop_index(op.f('ix_run_events_agent_run_id'), table_name='run_events')
    op.drop_table('run_events')
    # ### end Alembic commands ###
