"""add evidence item title

Revision ID: 62cd66038dbc
Revises: bcce9d359f3c
Create Date: 2026-08-20 02:49:58.054699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62cd66038dbc'
down_revision: Union[str, Sequence[str], None] = 'bcce9d359f3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence_items', sa.Column('title', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evidence_items', 'title')
    # ### end Alembic commands ###
