"""add evidence category

Revision ID: 64d60facd265
Revises: 221ed4e547b9
Create Date: 2026-08-19 17:18:03.658577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64d60facd265'
down_revision: Union[str, Sequence[str], None] = '221ed4e547b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default, not just the Python-side model default — this
    # table already has rows (autogenerate produced a bare NOT NULL
    # add_column, which fails on an existing table; caught by hand
    # review, not by running it, since the failure mode is well known
    # rather than one that needed live discovery).
    op.add_column(
        'evidence_items',
        sa.Column('category', sa.String(length=20), nullable=False, server_default='other'),
    )
    op.create_index(op.f('ix_evidence_items_category'), 'evidence_items', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_items_category'), table_name='evidence_items')
    op.drop_column('evidence_items', 'category')
    # ### end Alembic commands ###
