"""M2 preferences and company candidates

Revision ID: 7fde5adc9727
Revises: 5cd8a15cdcbc
Create Date: 2026-08-21 07:53:45.148709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fde5adc9727'
down_revision: Union[str, Sequence[str], None] = '5cd8a15cdcbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-reviewed: autogenerate's bare NOT NULL add_column calls below
    # would fail outright against this real dev DB — checked directly,
    # not assumed: personas has 1 row, fit_scores 91, prefilter_results
    # 93. server_defaults added below matching each column's Python-side
    # default, same fix as M1's bcce9d359f3c migration for the same bug
    # class. preferences currently has 0 rows (never wired up before
    # M2), so willing_to_relocate's default is precautionary, not load-
    # bearing today.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_candidates',
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=250), nullable=False),
    sa.Column('origin', sa.String(length=30), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('resolved_identifier', sa.String(length=250), nullable=True),
    sa.Column('discovered_url', sa.String(length=1000), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('origin_job_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['origin_job_id'], ['jobs.id'], name=op.f('fk_company_candidates_origin_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], name=op.f('fk_company_candidates_persona_id_personas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_candidates')),
    sa.UniqueConstraint('persona_id', 'company_name', name='uq_company_candidates_persona_name')
    )
    op.create_index(op.f('ix_company_candidates_user_id'), 'company_candidates', ['user_id'], unique=False)
    op.add_column('fit_scores', sa.Column('persona_revision', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('personas', sa.Column('revision', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('preferences', sa.Column('willing_to_relocate', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('prefilter_results', sa.Column('persona_revision', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prefilter_results', 'persona_revision')
    op.drop_column('preferences', 'willing_to_relocate')
    op.drop_column('personas', 'revision')
    op.drop_column('fit_scores', 'persona_revision')
    op.drop_index(op.f('ix_company_candidates_user_id'), table_name='company_candidates')
    op.drop_table('company_candidates')
    # ### end Alembic commands ###
