"""credit_ledger_phase16

Revision ID: 864362edc258
Revises: b7dda14ad62d
Create Date: 2026-09-04 02:30:58.084863

Phase 16 — credit-based billing. Adds the ledger tables (append-only
CreditTransaction, admin-managed FeatureCreditCost/CreditPack price
lists) and Plan.monthly_credits, then seeds starting data: feature
costs, credit packs, and each plan's monthly credit allotment. Also
rescales Unemployed/Super Unemployed's price to roughly match their
new, smaller credit allotments (confirmed with Adrian directly) — real
Rp numbers, not derived from anything, tune later via the admin Plans
page same as any other Plan field. NOTE: this does NOT touch either
plan's already-provisioned Dodo product (dodo_product_id_test is set
for both, confirmed live) — a schema migration has no business making
live API calls; whoever deploys this should re-save both plans once
from the admin Plans page (or run billing_service.sync_product_for_plan
directly) so the real Dodo product price actually matches what's in
this table, not just what's shown in the app.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '864362edc258'
down_revision: Union[str, Sequence[str], None] = 'b7dda14ad62d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_packs',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('price_idr', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('dodo_product_id_test', sa.String(length=120), nullable=True),
    sa.Column('dodo_product_id_live', sa.String(length=120), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_packs'))
    )
    op.create_table('feature_credit_costs',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('credit_cost', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_credit_costs')),
    sa.UniqueConstraint('key', name=op.f('uq_feature_credit_costs_key'))
    )
    op.create_table('credit_transactions',
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('bucket', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('admin_user_id', sa.UUID(), nullable=True),
    sa.Column('feature_key', sa.String(length=60), nullable=True),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('credit_purchase_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], name=op.f('fk_credit_transactions_admin_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_credit_transactions_agent_run_id_agent_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['credit_purchase_id'], ['credit_packs.id'], name=op.f('fk_credit_transactions_credit_purchase_id_credit_packs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_transactions'))
    )
    op.create_index(op.f('ix_credit_transactions_user_id'), 'credit_transactions', ['user_id'], unique=False)
    # nullable at first (existing Plan rows have no value yet) —
    # backfilled below, then locked to NOT NULL, same shape any other
    # migration in this repo backfilling a new required column uses.
    op.add_column('plans', sa.Column('monthly_credits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    # --- Phase 16 seed data ---

    # Plan credit allotments — Free is a ONE-TIME grant (never refreshed,
    # see credit_ledger.grant_monthly_credits), Unemployed/Super
    # Unemployed are real monthly grants. Roughly $1 / $2 / $5 worth at
    # an internal-only ~$0.02/credit anchor — never surfaced anywhere,
    # purely how these starting numbers were picked.
    op.execute("UPDATE plans SET monthly_credits = 50 WHERE name = 'Open to Work'")
    op.execute("UPDATE plans SET monthly_credits = 100 WHERE name = 'Unemployed'")
    op.execute("UPDATE plans SET monthly_credits = 250 WHERE name = 'Super Unemployed'")
    # Rescaled prices to roughly match the smaller credit allotments
    # above (confirmed directly with Adrian) — real Rp numbers, tune
    # later via the admin Plans page like any other Plan field.
    op.execute("UPDATE plans SET price_idr = 40000 WHERE name = 'Unemployed'")
    op.execute("UPDATE plans SET price_idr = 95000 WHERE name = 'Super Unemployed'")
    op.alter_column('plans', 'monthly_credits', nullable=False)

    op.execute("""
        INSERT INTO feature_credit_costs (id, key, display_name, credit_cost, is_active, created_at, updated_at)
        VALUES
            (gen_random_uuid(), 'cv-tailor', 'Tailor / edit a CV', 20, true, now(), now()),
            (gen_random_uuid(), 'cover-letter', 'Generate a cover letter', 15, true, now(), now()),
            (gen_random_uuid(), 'answer-pack', 'Generate an answer pack', 10, true, now(), now()),
            (gen_random_uuid(), 'radar-run', 'Run a job search', 8, true, now(), now()),
            (gen_random_uuid(), 'application-apply', 'Apply with the agent', 20, true, now(), now()),
            (gen_random_uuid(), 'interview-practice', 'Practice an interview (per session)', 30, true, now(), now()),
            (gen_random_uuid(), 'skill-gap-syllabus', 'Generate a learning plan', 8, true, now(), now())
        -- CV parsing deliberately has no row here at all — free, on the house.
    """)

    op.execute("""
        INSERT INTO credit_packs (id, name, price_idr, credits, is_active, created_at, updated_at)
        VALUES
            (gen_random_uuid(), 'Small', 20000, 50, true, now(), now()),
            (gen_random_uuid(), 'Medium', 45000, 120, true, now(), now()),
            (gen_random_uuid(), 'Large', 85000, 250, true, now(), now())
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'monthly_credits')
    op.drop_index(op.f('ix_credit_transactions_user_id'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_table('feature_credit_costs')
    op.drop_table('credit_packs')
    # ### end Alembic commands ###
