"""m4_application_execution_schema

Revision ID: 932bf23ce1f2
Revises: 2a090e5a512b
Create Date: 2026-08-21 17:56:50.214492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # autogenerate emits fully-qualified HALFVEC refs but omits this import
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '932bf23ce1f2'
down_revision: Union[str, Sequence[str], None] = '2a090e5a512b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('browser_contexts',
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('storage_state_key', sa.String(length=512), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], name=op.f('fk_browser_contexts_persona_id_personas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_browser_contexts_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_browser_contexts'))
    )
    op.create_index(op.f('ix_browser_contexts_user_id'), 'browser_contexts', ['user_id'], unique=False)
    op.create_table('application_attempts',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('autonomy_level', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('field_map', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('screenshot_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_application_attempts_agent_run_id_agent_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_attempts_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_attempts'))
    )
    op.create_table('form_answers',
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_embedding', pgvector.sqlalchemy.halfvec.HALFVEC(dim=2048), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('source_application_id', sa.UUID(), nullable=True),
    sa.Column('times_reused', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], name=op.f('fk_form_answers_persona_id_personas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_application_id'], ['applications.id'], name=op.f('fk_form_answers_source_application_id_applications'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_form_answers'))
    )
    op.create_index('ix_form_answers_embedding_hnsw', 'form_answers', ['question_embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'question_embedding': 'halfvec_l2_ops'})
    op.create_index(op.f('ix_form_answers_user_id'), 'form_answers', ['user_id'], unique=False)
    op.add_column('applications', sa.Column('job_group_id', sa.UUID(), nullable=True))
    op.add_column('applications', sa.Column('primary_document_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_applications_primary_document_id_documents'), 'applications', 'documents', ['primary_document_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_applications_job_group_id_job_groups'), 'applications', 'job_groups', ['job_group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_applications_job_group_id_job_groups'), 'applications', type_='foreignkey')
    op.drop_constraint(op.f('fk_applications_primary_document_id_documents'), 'applications', type_='foreignkey')
    op.drop_column('applications', 'primary_document_id')
    op.drop_column('applications', 'job_group_id')
    op.drop_index(op.f('ix_form_answers_user_id'), table_name='form_answers')
    op.drop_index('ix_form_answers_embedding_hnsw', table_name='form_answers', postgresql_using='hnsw', postgresql_ops={'question_embedding': 'halfvec_l2_ops'})
    op.drop_table('form_answers')
    op.drop_table('application_attempts')
    op.drop_index(op.f('ix_browser_contexts_user_id'), table_name='browser_contexts')
    op.drop_table('browser_contexts')
    # ### end Alembic commands ###
