"""audio settings secondary voice

Revision ID: b7dda14ad62d
Revises: c2bf6482c643
Create Date: 2026-09-03 08:28:41.368611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7dda14ad62d'
down_revision: Union[str, Sequence[str], None] = 'c2bf6482c643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_settings', sa.Column('speech_voice_secondary', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_settings', 'speech_voice_secondary')
    # ### end Alembic commands ###
