"""M1 schema delta: canonical key, prefilter results, sighting uniqueness, cost attribution

Revision ID: bcce9d359f3c
Revises: 9f5a6d3c1b72
Create Date: 2026-08-20 02:33:00.632805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bcce9d359f3c'
down_revision: Union[str, Sequence[str], None] = '9f5a6d3c1b72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-reviewed: jobs/fit_scores/saved_searches/source_runs are all
    # empty right now (checked against the real container before writing
    # this), so autogenerate's bare NOT NULL add_column calls below would
    # actually succeed as-is — but server_defaults are added anyway,
    # matching each column's Python-side model default, so this doesn't
    # silently break the next time this migration path is exercised
    # against a populated dev DB. Exactly the bug class caught in the
    # M0 "add evidence category" migration; not repeating it.
    # canonical_key is the one deliberate exception — there is no
    # sensible universal default for a dedup key, so it stays a bare
    # NOT NULL and simply requires `jobs` to be empty, which it is.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prefilter_results',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('profile_revision', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('prefilter_version', sa.String(length=40), nullable=False),
    sa.Column('model_used', sa.String(length=120), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_prefilter_results_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], name=op.f('fk_prefilter_results_persona_id_personas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prefilter_results'))
    )
    op.create_index(op.f('ix_prefilter_results_user_id'), 'prefilter_results', ['user_id'], unique=False)
    op.add_column('agent_runs', sa.Column('saved_search_id', sa.UUID(), nullable=True))
    op.add_column('agent_runs', sa.Column('persona_id', sa.UUID(), nullable=True))
    op.add_column('agent_runs', sa.Column('profile_revision', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_agent_runs_persona_id_personas'), 'agent_runs', 'personas', ['persona_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_agent_runs_saved_search_id_saved_searches'), 'agent_runs', 'saved_searches', ['saved_search_id'], ['id'], ondelete='SET NULL')
    op.add_column('fit_scores', sa.Column('scoring_version', sa.String(length=40), nullable=False, server_default='v1'))
    op.create_unique_constraint('uq_job_sightings_source_requisition', 'job_sightings', ['source_id', 'external_requisition_id'])
    op.add_column('jobs', sa.Column('canonical_key', sa.String(length=500), nullable=False))
    op.add_column('jobs', sa.Column('ghost_job_reasons', postgresql.ARRAY(sa.String()), nullable=False, server_default='{}'))
    op.create_index(op.f('ix_jobs_canonical_key'), 'jobs', ['canonical_key'], unique=False)
    op.create_foreign_key(op.f('fk_jobs_preferred_sighting_id_job_sightings'), 'jobs', 'job_sightings', ['preferred_sighting_id'], ['id'], ondelete='SET NULL')
    op.add_column('llm_calls', sa.Column('job_id', sa.UUID(), nullable=True))
    op.add_column('llm_calls', sa.Column('source_run_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_llm_calls_source_run_id_source_runs'), 'llm_calls', 'source_runs', ['source_run_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_llm_calls_job_id_jobs'), 'llm_calls', 'jobs', ['job_id'], ['id'], ondelete='SET NULL')
    op.add_column('saved_searches', sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    op.add_column('source_runs', sa.Column('status', sa.String(length=20), nullable=False, server_default='pending'))
    op.add_column('source_runs', sa.Column('expanded_queries', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_runs', 'expanded_queries')
    op.drop_column('source_runs', 'status')
    op.drop_column('saved_searches', 'filters')
    op.drop_constraint(op.f('fk_llm_calls_job_id_jobs'), 'llm_calls', type_='foreignkey')
    op.drop_constraint(op.f('fk_llm_calls_source_run_id_source_runs'), 'llm_calls', type_='foreignkey')
    op.drop_column('llm_calls', 'source_run_id')
    op.drop_column('llm_calls', 'job_id')
    op.drop_constraint(op.f('fk_jobs_preferred_sighting_id_job_sightings'), 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_canonical_key'), table_name='jobs')
    op.drop_column('jobs', 'ghost_job_reasons')
    op.drop_column('jobs', 'canonical_key')
    op.drop_constraint('uq_job_sightings_source_requisition', 'job_sightings', type_='unique')
    op.drop_column('fit_scores', 'scoring_version')
    op.drop_constraint(op.f('fk_agent_runs_saved_search_id_saved_searches'), 'agent_runs', type_='foreignkey')
    op.drop_constraint(op.f('fk_agent_runs_persona_id_personas'), 'agent_runs', type_='foreignkey')
    op.drop_column('agent_runs', 'profile_revision')
    op.drop_column('agent_runs', 'persona_id')
    op.drop_column('agent_runs', 'saved_search_id')
    op.drop_index(op.f('ix_prefilter_results_user_id'), table_name='prefilter_results')
    op.drop_table('prefilter_results')
    # ### end Alembic commands ###
