"""audio catalog pricing per minute and per character

Revision ID: c2bf6482c643
Revises: 4503b55a4b56
Create Date: 2026-09-03 06:21:38.385587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2bf6482c643'
down_revision: Union[str, Sequence[str], None] = '4503b55a4b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_catalog_entries', sa.Column('price_per_minute', sa.Numeric(precision=12, scale=6), nullable=True))
    op.add_column('model_catalog_entries', sa.Column('price_per_character', sa.Numeric(precision=12, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_catalog_entries', 'price_per_character')
    op.drop_column('model_catalog_entries', 'price_per_minute')
    # ### end Alembic commands ###
