"""add source status tracking

Revision ID: e67767471f95
Revises: 62cd66038dbc
Create Date: 2026-08-20 03:56:14.540064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e67767471f95'
down_revision: Union[str, Sequence[str], None] = '62cd66038dbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default so this doesn't break on a populated `sources`
    # table (same NOT-NULL-without-default trap as M0/M1's earlier
    # migrations — table happens to be empty right now, checked
    # directly, but fixed properly anyway rather than leave the trap
    # for whoever runs this migration against real data later).
    op.add_column(
        'sources', sa.Column('status', sa.String(length=20), nullable=False, server_default='untested')
    )
    op.add_column('sources', sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sources', sa.Column('last_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'last_error')
    op.drop_column('sources', 'last_verified_at')
    op.drop_column('sources', 'status')
    # ### end Alembic commands ###
