"""M2 source run company breakdown

Revision ID: f35e8b06ed03
Revises: 547887ea6409
Create Date: 2026-08-21 09:15:44.749524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f35e8b06ed03'
down_revision: Union[str, Sequence[str], None] = '547887ea6409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-reviewed: 11 real source_runs rows exist (checked directly,
    # not assumed) — the bare NOT NULL add_column autogenerate produced
    # would fail outright, same bug class as every prior migration this
    # milestone. server_default added to match the model's own default.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'source_runs',
        sa.Column(
            'company_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_runs', 'company_breakdown')
    # ### end Alembic commands ###
