"""add source_run agent_run_id

Revision ID: f93e681079f8
Revises: e67767471f95
Create Date: 2026-08-20 13:26:32.174142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f93e681079f8'
down_revision: Union[str, Sequence[str], None] = 'e67767471f95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_runs', sa.Column('agent_run_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_source_runs_agent_run_id_agent_runs'), 'source_runs', 'agent_runs', ['agent_run_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_source_runs_agent_run_id_agent_runs'), 'source_runs', type_='foreignkey')
    op.drop_column('source_runs', 'agent_run_id')
    # ### end Alembic commands ###
